---
title: "Stock_Trading_Analysis"
output: html_document
---



```{r echo=F, warning=F, message=F}
filenames=list.files(pattern = "^Depot") #get .csv files beginning with the string "Depot"
lst_date=lapply(filenames, read.delim, sep=";") # read all of them into a list seperated by semicolon
lst_date=lapply(lst_date, function(x) x$Exportdatum) #extract the column which contains the date
vec_date=unlist(lapply(lst_date, `[[`,1)) # extract the very first value & convert list to single vector
vec_date=sub(" .*", "", vec_date) # get rid of the time as we only need the date
date=as.Date(vec_date, "%d.%m.%y") # convert date from character format to date format
#date
```

```{r echo=F, warning=F, message=F}
filenames=list.files(pattern = "^Depot") #get .csv files beginning with the string "Depot"
lst=lapply(filenames, read.delim, sep=";", skip=6, dec=",") # read all of them into a list, skip some rows due to redundancy & convert commas to dots
t_lst = lapply(lst, function(x) {
   x <- x[,c(1,3,5,7,9,11)] # keep only desired columns
   colnames(x)[3:6] <- c("share_Pctn","profit_Euro","profit_Pctn","dividend_2021") # rename columns
   x <- x[x$Gattung=="Aktie",] # keep only stocks
   x <- x[,-2] # delete column "Gattung"
   tx = setNames(data.frame(t(x[,-1])), x[,1])
   return(tx)
  })
```


## Stock shares & dividend 2021

```{r echo=F, warning=F, message=F}
library(dplyr)

df_share=lapply(t_lst, function(x) x[1,]) # extract share row
df_share=bind_rows(df_share) # concatenate nested df into one df rowwise
df_share=cbind(date, df_share) # concatenate stocks with their corresponding date
rownames(df_share) <- NULL # delete index column which appears out of nowhere
df_share=df_share[order(as.Date(df_share$date, format="%d/%m/%Y")),] #order df by for the next step
df_share=df_share[ , is.na(df_share[nrow(df_share),]) == 0] # remove stocks with no share

library(tidyr)
df_share_l <- gather(df_share, Name, share, `ALLIANZ SE NA O.N.`:`RIOCAN REAL ESTATE INV.`, factor_key=TRUE) # convert from wide to long format #TODO: access directly to the first and last stock instead of using the specific stock name

library(scales)
df_share_l$share=round(df_share_l$share,1) # round to one decimal digit

```

```{r echo=F, warning=F, message=F}
library(dplyr)
df_dividend=lapply(t_lst, function(x) x[4,]) # extract dividend row
df_dividend=bind_rows(df_dividend) # concatenate nested df into one df rowwise
df_dividend=cbind(date, df_dividend) # concatenate stocks with their corresponding date
rownames(df_dividend) <- NULL # delete index column which appears out of nowhere
df_dividend=df_dividend[order(as.Date(df_dividend$date, format="%d/%m/%Y")),] #order df by for the next step
df_dividend=df_dividend[nrow(df_dividend),-1] # take the dividend proportion of the latest date
df_dividend=df_dividend[ , colSums(is.na(df_dividend)) == 0] # remove stocks with no dividend

library(tidyr)
df_dividend_l <- gather(df_dividend, Name, dividend, `ALLIANZ SE NA O.N.`:`RIOCAN REAL ESTATE INV.`, factor_key=TRUE) # convert from wide to long format #TODO: access directly to the first and last stock instead of using the specific stock name

a=data.frame(Name="MEYER BUR.TECH.NAM.SF-,05", dividend=0)
b=data.frame(Name="BED BATH + BEYOND DL-,01", dividend=0)
a$Name=as.factor(a$Name)
b$Name=as.factor(b$Name)
df_dividend_l=rbind(df_dividend_l,a,b)

library(scales)
df_dividend_l$dividend=round(df_dividend_l$dividend,1) # round to one decimal digit
```

### shares + dividend

```{r echo=F, warning=F, message=F, fig.height=5, fig.width=8}
df_share_l$share=-(df_share_l$share)

library(data.table)
df_share_l_sub=setDT(df_share_l)[,.SD[which.max(date)],keyby=Name]

df=merge(df_share_l_sub[,-2],df_dividend_l,by="Name")
test= gather(df, condition, measurement, share:dividend, factor_key=TRUE)

#df$dividend=-(df$dividend)
test= gather(df, condition, measurement, share:dividend, factor_key=TRUE)
test$share=c(rep(test[test$condition=="share",3],2))

#test$condition=factor(test$condition, levels = c("dividend","share"))
library(ggplot2)

p_share=ggplot(test,aes(y =reorder(Name,-share),x = measurement, fill = condition)) +
    geom_col( position = position_dodge(width = 0),  colour = "black", width = 0.5) +
  scale_x_continuous(labels = function(x){ 
     #paste0(x, "%")
      if_else(x<0, -x, x) 
    },breaks = c(seq(-24,24,by=2))) +
  theme_classic()+
  geom_vline(aes(xintercept = 0)) +
 theme(axis.title.x = element_blank(), axis.title.y = element_blank())+
 scale_fill_manual(values = c("white", "gray75"), guide =F)+
  geom_vline(xintercept = -5, linetype="dashed", color="red")

library(plotly)
ggplotly(p_share)
```

## Performing in Euro & %

```{r echo=F}
lst_total=lapply(filenames, read.delim, sep=";", skip=3,nrows=1) # read all of them into a list, skip some rows due to redundancy & convert commas to dots
t_lst_total = lapply(lst_total, function(x) {
   x <- x[,1] # keep only desired columns
   x=gsub(',.*', '', x)
   x=gsub('\\.', '', x)
   x=as.numeric(x)
   return(x)
  })
depotwert=cbind(date,bind_rows(lapply(t_lst_total, setNames, nm = "Gesamtdepotwert")))
depotwert=depotwert[order(as.Date(depotwert$date, format="%Y/%m/%d")),]
depotwert$baseline=c(rep(29000, 4),27000,27000,27000,rep(29000, nrow(depotwert)-7))
depotwert$total_Euro=depotwert$Gesamtdepotwert-depotwert$baseline
depotwert$total_Pctn=round((depotwert$total_Euro/depotwert$baseline)*100,1)
total=depotwert[nrow(depotwert),c(1,4,5)]
total_l=gather(total, condition, profit, total_Euro:total_Pctn, factor_key ="date")
total_l$condition=ifelse(total_l$condition=="total_Euro", "Euro", "%")
total_l$share=-100
total_l$ind=ifelse(total_l$profit>0, "positive", "negative")
total_l$profit=ifelse(total_l$condition=="%", -abs(total_l$profit)*10, abs(total_l$profit))
total_l$Name="Total Profit"
total_l$date=NULL
total_l=total_l[,c(5,1,2,3,4)]
```

```{r echo=F, fig.height=5, fig.width=8}
df_profit=lapply(t_lst, function(x) x[c(2,3),])
df_profit=bind_rows(df_profit)
df_profit=setDT(df_profit, keep.rownames = TRUE)[]
df_profit$rn=gsub("\\..*","",df_profit$rn)

df_profit_Pctn=df_profit[df_profit$rn=="profit_Pctn",]
df_profit_Euro=df_profit[df_profit$rn=="profit_Euro",]

df_profit_Pctn=cbind(date, df_profit_Pctn)
df_profit_Euro=cbind(date, df_profit_Euro)

df_profit_Pctn_l <- gather(df_profit_Pctn, Name, profit, AIRBUS:`GAMESTOP CORP. A`, factor_key=TRUE)
df_profit_Pctn_l_sub=setDT(df_profit_Pctn_l)[,.SD[which.max(date)],keyby=Name]
df_profit_Euro_l <- gather(df_profit_Euro, Name, profit, AIRBUS:`GAMESTOP CORP. A`, factor_key=TRUE)
df_profit_Euro_l_sub=setDT(df_profit_Euro_l)[,.SD[which.max(date)],keyby=Name]

df_profit_l=rbind(df_profit_Pctn_l_sub,df_profit_Euro_l_sub)
df_profit_l=df_profit_l[complete.cases(df_profit_l), ]
df_profit_l=merge(df_profit_l,test[test$condition=="share",], by="Name")
df_profit_l=df_profit_l[,c(1:4,7)]
df_profit_l$rn=as.factor(df_profit_l$rn)
df_profit_l$ind=ifelse(df_profit_l$profit>0, "positive","negative")
df_profit_l$ind=as.factor(df_profit_l$ind)

test2=df_profit_l[,-2]
test2$profit=ifelse(test2$rn=="profit_Pctn", -abs(test2$profit)*10, abs(test2$profit))

test2$rn=factor(test2$rn, labels=c("Euro","%"))
colnames(test2)[2]="condition"
test2=rbind(test2, total_l)


p=ggplot(test2,aes(y =reorder(Name,-share),x = profit, fill = ind, group=ind, alpha=condition)) +
    geom_bar(stat="identity",position="dodge", colour="black") +
  theme_classic()+
  scale_x_continuous(labels = function(x) if_else(x<0, -x/10, x), 
  breaks = function(x) as.integer(c(seq(-400, 1000,100))), limits = c(-400,1000)) +  
  geom_vline(aes(xintercept = 0)) +
 theme(axis.title.x = element_blank(), axis.title.y = element_blank())+
  labs(fill = "Performance (+|-)", alpha="Unit (Euro | %)")+
  scale_fill_manual(values=c("red","green"))
  
ggplotly(p)
```

## Profit chronological

```{r echo=F, fig.height=8, fig.width=5}
df_profitPctn=lapply(t_lst, function(x) x[3,]) # extract profitPctn row
df_profitPctn=bind_rows(df_profitPctn) # concatenate nested df into one df rowwise
df_profitPctn=cbind(date, df_profitPctn) # concatenate stocks with their corresponding date
rownames(df_profitPctn) <- NULL # delete index column which appears out of nowhere
df_profitPctn=df_profitPctn[order(as.Date(df_profitPctn$date, format="%d/%m/%Y")),] #order df by for the next step
df_profitPctn=df_profitPctn[ , is.na(df_profitPctn[nrow(df_profitPctn),]) == 0] # remove stocks with no profitPctn

library(tidyr)
df_profitPctn_l <- gather(df_profitPctn, Name, profitPctn, `ALLIANZ SE NA O.N.`:`RIOCAN REAL ESTATE INV.`, factor_key=TRUE) # convert from wide to long format #TODO: access directly to the first and last stock instead of using the specific stock name

library(scales)
df_profitPctn_l$profitPctn=round(df_profitPctn_l$profitPctn,1) # round to one decimal digit


library(ggplot2)
p_profitPctn=ggplot(df_profitPctn_l, aes(x=date,y=profitPctn, color=Name, group=Name ))+
  geom_line()+
  theme_bw()+
  geom_hline(yintercept = 0, linetype="dashed", color="black")+
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle = 30) )+
 scale_y_continuous(labels = function(x) paste0(x, "%"))

library(plotly)
ggplotly(p_profitPctn)
```


## Total Profit chronological

```{r echo=F}
lst_total=lapply(filenames, read.delim, sep=";", skip=3,nrows=1) # read all of them into a list, skip some rows due to redundancy & convert commas to dots
t_lst_total = lapply(lst_total, function(x) {
   x <- x[,1] # keep only desired columns
   x=gsub(',.*', '', x)
   x=gsub('\\.', '', x)
   x=as.numeric(x)
   return(x)
  })
depotwert=cbind(date,bind_rows(lapply(t_lst_total, setNames, nm = "Gesamtdepotwert")))
depotwert=depotwert[order(as.Date(depotwert$date, format="%Y/%m/%d")),]
depotwert$baseline=c(rep(29000, 4),27000,27000,27000,rep(29000, nrow(depotwert)-7))
depotwert$total_Euro=depotwert$Gesamtdepotwert-depotwert$baseline
depotwert$total_Pctn=round((depotwert$total_Euro/depotwert$baseline)*100,1)
total=depotwert[,c(1,4,5)]
total_l=gather(total, condition, profit, total_Euro:total_Pctn, factor_key ="date")
total_l$condition=ifelse(total_l$condition=="total_Euro", "Euro", "%")
total_l$ind=ifelse(total_l$profit>0, "positive", "negative")
total_l$profit=ifelse(total_l$condition=="%", -abs(total_l$profit)*100, abs(total_l$profit))
total_l$Name="Total Profit"
#total_l
```


```{r echo=F, warning=F, message=F, fig.height=8, fig.width=5}
p=ggplot(total_l,aes(x =date,y = profit, fill = as.factor(ind), group=as.factor(ind),     alpha=as.factor(condition))) +
  geom_bar(stat="identity",position="dodge", colour="black") +
  theme_bw()+
  scale_y_continuous(labels = function(x) if_else(x<0, -x/100, x),
  breaks = function(x) as.integer(c(seq(-400, 1000,100))), limits = c(-400,1000)) +  
  geom_vline(aes(xintercept = 0)) +
 theme(axis.title.x = element_blank(), axis.title.y = element_blank(),axis.text.x = element_text(angle = 90))+
  labs(fill = "Performance (+|-)", alpha="Unit (Euro | %)")+
  scale_fill_manual(values=c("red","green"))+
  scale_x_date(date_breaks = "1 day", date_labels = "%Y-%m-%d")+
  geom_hline(yintercept = 0)

ggplotly(p)
```



## Closed Orders

```{r echo=F, fig.height=8, fig.width=5}
closed=read.csv("./Abgeschlossene_Geschäfte.csv", sep=";", dec=",", header=T, skip=3)
closed=closed[closed$Gattung=="Aktien",c(1,3,5)]
closed$Gattung=NULL
colnames(closed)[2]="Profit"
closed$ind=ifelse(closed$Profit>=0, "positive","negative")
closed[nrow(closed)+1,]=c("Total Profit", sum(closed$Profit),"Total Profit")
closed$Profit=as.numeric(closed$Profit)

p_closed=ggplot(closed, aes(y=reorder(Name,Profit), x=Profit, fill=ind))+
  geom_bar(stat="identity",width=0.8)+
  theme_bw()+
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())+
  geom_vline(xintercept = 0)

ggplotly(p_closed)
```

### Order history

```{r echo=F}
order_hist=read.csv("./Orderübersicht.csv", sep=";", dec=",")
order_hist=order_hist[order_hist$Name!="X(IE)-MSCI WORLD 1C" & order_hist$Name!="MUL-LYX.NASDAQ-100 UE A" & order_hist$Name!="HSBC MSCI WORLD UCITS ETF"  & order_hist$Name!="LYX.IF-ROB.AI DLA" & order_hist$Name!="X(IE)-MSCI EM.MKTS 1CDL" & order_hist$Name!="X(IE)-MSCI EM.MKTS 1CDL",c(1,3,11),]
colnames(order_hist)=c("Type","Name","Orderdate")

order_hist$Orderdate=as.Date(order_hist$Orderdate, format = "%d.%m.%y")
#order_hist=order_hist[order(order_hist$Orderdate),]
order_hist$ind=1
order_hist$ind2=ifelse(order_hist$Type=="Kauf",1,-1)
```

```{r echo=F, fig.width=10, fig.height=20, m}
ggplot(order_hist, aes(x=Orderdate,y=ind2, fill=Type ))+
  geom_col(position = "identity")+
   theme_bw()+
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle = 90))+
  geom_hline(yintercept = 0)+
annotate("text", x = as.Date("2021-01-04",format = "%Y-%m-%d"), y = 2,size=3, label = "Xiaomi",color="blue",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-05",format = "%Y-%m-%d"), y = 2, size=3,label = "Transalta Renew., Vestas wind, Sony, Samsung, Westwing",color="blue",hjust = 0,vjust=1)+
  annotate("text", x = as.Date("2021-01-05",format = "%Y-%m-%d"), y = 2, size=3,label = "Nel Asa, CD Projekt, Ballard Pwr, Alibaba, TUI,",color="blue",hjust = 0,vjust=-0.5)+
  
annotate("text", x = as.Date("2021-01-06",format = "%Y-%m-%d"), y = 2, size=3,label = "Alibaba",color="blue",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-07",format = "%Y-%m-%d"), y =2, size=3,label = "Vestas Wind, TUI, Nel Asa, Ballard Pwr, Transalta Renew.",color="blue",hjust = 0)+

annotate("text", x = as.Date("2021-01-08",format = "%Y-%m-%d"), y = 2, size=3,label = "Infineon, Plug Pwr, Siemens",color="blue",hjust = 0)+
annotate("text", x = as.Date("2021-01-08",format = "%Y-%m-%d"), y = -20, size=3,label = "CD Projekt, Alibaba, Westwing, Vestas wind, TUI",color="orange3",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-11",format = "%Y-%m-%d"), y = -20, size=3,label = "Sony,Ballard Pwr",color="orange3",hjust = 0)+
annotate("text", x = as.Date("2021-01-11",format = "%Y-%m-%d"), y = 2, size=3,label = "Nio, Bristol Myers",color="blue",hjust = 0)+  
  
annotate("text", x = as.Date("2021-01-12",format = "%Y-%m-%d"), y = -20, size=3,label = "Plug Pwr",color="orange3",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-13",format = "%Y-%m-%d"), y = -20, size=3,label = "Vestas wind, Nio",color="orange3",hjust = 0)+
annotate("text", x = as.Date("2021-01-13",format = "%Y-%m-%d"), y = 2, size=3,label = "Veewa Systems,Cadence Design, Bristol Myers,Xiaomi,Infineon,Microsoft",color="blue",hjust = 0)+   

annotate("text", x = as.Date("2021-01-14",format = "%Y-%m-%d"), y = 2, size=3,label = "Hut 8 Mining",color="blue",hjust = 0)+    
  
annotate("text", x = as.Date("2021-01-18",format = "%Y-%m-%d"), y = -25, size=3,label = "Alibaba, Bristol Myers, Samsung, Cadence Design,",color="orange3",hjust =0, vjust=-0.5)+
annotate("text", x = as.Date("2021-01-18",format = "%Y-%m-%d"), y = -25, size=3,label = "Siemens, Infineon, Transalta Renew., Nel Asa",color="orange3",hjust = 0, vjust=1)+
annotate("text", x = as.Date("2021-01-18",format = "%Y-%m-%d"), y = 2, size=3,label = "Tencent, Apple, Palantir, Square, Teladoc Health, Moderna,",color="blue",hjust = 0, vjust=-0.5)+ 
annotate("text", x = as.Date("2021-01-18",format = "%Y-%m-%d"), y = 2, size=3,label = "Paypal, BBBY, Bristol M.",color="blue",hjust = 0, vjust=1)+   
  
annotate("text", x = as.Date("2021-01-19",format = "%Y-%m-%d"), y = -20, size=3,label = "Veeva systems, Teladoc Health, Paypal, Apple",color="orange3",hjust = 0, vjust=1)+ 
annotate("text", x = as.Date("2021-01-19",format = "%Y-%m-%d"), y = -20, size=3,label = "Moderna, Square, Microsoft, Nel Asa",color="orange3",hjust = 0, vjust=-0.5)+ 
annotate("text", x = as.Date("2021-01-19",format = "%Y-%m-%d"), y = 2, size=3,label = "Xinyi Solar",color="blue",hjust = 0, vjust=1)+   
  
annotate("text", x = as.Date("2021-01-20",format = "%Y-%m-%d"), y = 2, size=3,label = "Xiaomi, Xinyi Solar",color="blue",hjust = 0)+     
  
annotate("text", x = as.Date("2021-01-21",format = "%Y-%m-%d"), y = -20, size=3,label = "Hut 8 Mining",color="orange3",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-22",format = "%Y-%m-%d"), y = -20, size=3,label = "Bristol Myers, Palantir, Xiaomi",color="orange3",hjust = 0)+
annotate("text", x = as.Date("2021-01-22",format = "%Y-%m-%d"), y = 2, size=3,label = "BBBY, Tencent",color="blue",hjust = 0)+  
  
annotate("text", x = as.Date("2021-01-25",format = "%Y-%m-%d"), y = 2, size=3,label = "The Naga Group",color="blue",hjust = 0)+

annotate("text", x = as.Date("2021-01-26",format = "%Y-%m-%d"), y = 2, size=3,label = "McDonalds",color="blue",hjust = 0)+

annotate("text", x = as.Date("2021-01-27",format = "%Y-%m-%d"), y = 2, size=3,label = "McDonalds",color="blue",hjust = 0)+
annotate("text", x = as.Date("2021-01-27",format = "%Y-%m-%d"), y = -20, size=3,label = "BBBY",color="orange3",hjust = 0)+
  
annotate("text", x = as.Date("2021-01-28",format = "%Y-%m-%d"), y = 2, size=3,label = "BBBY",color="blue",hjust = 0)+

  
annotate("text", x = as.Date("2021-01-29",format = "%Y-%m-%d"), y = 2, size=3,label = "BBBY",color="blue",hjust = 0)+
annotate("text", x = as.Date("2021-01-29",format = "%Y-%m-%d"), y = -20, size=3,label = "BBBY",color="orange3",hjust = 0)+
  
annotate("text", x = as.Date("2021-02-01",format = "%Y-%m-%d"), y = 2, size=3,label = "BBBY, Covestro, Wacker Chemie",color="blue",hjust = 0)+
annotate("text", x = as.Date("2021-02-01",format = "%Y-%m-%d"), y = -20, size=3,label = "BBBY",color="orange3",hjust = 0)+  
  
annotate("text", x = as.Date("2021-02-02",format = "%Y-%m-%d"), y = 2, size=3,label = "Paypal, Hella, Naga Group, Puma, Brenntag",color="blue",hjust = 0)+

annotate("text", x = as.Date("2021-02-03",format = "%Y-%m-%d"), y = 2, size=3,label = "Allianz,Aistron, Airbus, Siemens, Siemens Health, Siemens Energy,",color="blue",hjust = 0, vjust=-0.5)+ 
annotate("text", x = as.Date("2021-02-03",format = "%Y-%m-%d"), y = 2, size=3,label = "Altria Group, Coty, Dialog Semiconduct.,Lanxess, Pernod-Ricard",color="blue",hjust = 0, vjust=1)+ 
annotate("text", x = as.Date("2021-02-03",format = "%Y-%m-%d"), y = -30, size=3,label = "Dialog Semiconductor, Naga Group, Siemens, Coty, Altria Group",color="orange3",hjust = 0)+ 

annotate("text", x = as.Date("2021-02-04",format = "%Y-%m-%d"), y = 2, size=3,label = "Apple, Visa, Altria Group, Airbus",color="blue",hjust = 0, vjust=-0.5)+ 
annotate("text", x = as.Date("2021-02-04",format = "%Y-%m-%d"), y = 2, size=3,label = "Transalta Renew., Hollyfrontier, EPR Properties",color="blue",hjust = 0, vjust=1)+ 
 
annotate("text", x = as.Date("2021-02-05",format = "%Y-%m-%d"), y = 2, size=3,label = "Johnson + Johnson, Infineon, Meyer Burger",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-05",format = "%Y-%m-%d"), y = -30, size=3,label = "Wacker Chemie",color="orange3",hjust = 0)+   
  
annotate("text", x = as.Date("2021-02-08",format = "%Y-%m-%d"), y = 2, size=3,label = "Varta, Blizzard",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-08",format = "%Y-%m-%d"), y = -30, size=3,label = "Apple, Dialog Semicond.",color="orange3",hjust = 0)+    
  
annotate("text", x = as.Date("2021-02-08",format = "%Y-%m-%d"), y = 2, size=3,label = "Varta, Blizzard",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-08",format = "%Y-%m-%d"), y = -30, size=3,label = "Apple, Dialog Semicond.",color="orange3",hjust = 0)+      
  
annotate("text", x = as.Date("2021-02-10",format = "%Y-%m-%d"), y = 2, size=3,label = "Altria Grp, Coca-Cola",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-10",format = "%Y-%m-%d"), y = -30, size=3,label = "Aixtron, Brenntag",color="orange3",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-15",format = "%Y-%m-%d"), y = 2, size=3,label = "Meyer Burger",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-15",format = "%Y-%m-%d"), y = -30, size=3,label = "Apple, Lanxess, Blizzard",color="orange3",hjust = 0)+   
  
annotate("text", x = as.Date("2021-02-16",format = "%Y-%m-%d"), y = 2, size=3,label = "Sony",color="blue",hjust = 0)+ 
  
annotate("text", x = as.Date("2021-02-17",format = "%Y-%m-%d"), y = 2, size=3,label = "EPR Properties, Xiaomi",color="blue",hjust = 0)+
  
annotate("text", x = as.Date("2021-02-19",format = "%Y-%m-%d"), y = -30, size=3,label = "Hella GmbH",color="orange3",hjust = 0)+ 
  
annotate("text", x = as.Date("2021-02-22",format = "%Y-%m-%d"), y = 2, size=3,label = "Coty",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-22",format = "%Y-%m-%d"), y = -30, size=3,label = "Paypal, HollyFrontier",color="orange3",hjust = 0)+   
  
annotate("text", x = as.Date("2021-02-25",format = "%Y-%m-%d"), y = 2, size=3,label = "RWE, Altria Grp, Gamestop",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-02-25",format = "%Y-%m-%d"), y = -30, size=3,label = "Tencent, Gamestop",color="orange3",hjust = 0)+ 
  
annotate("text", x = as.Date("2021-02-26",format = "%Y-%m-%d"), y = 2, size=3,label = "Altria Grp",color="blue",hjust = 0)+ 

annotate("text", x = as.Date("2021-03-01",format = "%Y-%m-%d"), y = -25, size=3,label = "Siemens Health, EPR Properties, Puma, Sony,",color="orange3",hjust =0, vjust=-0.5)+
annotate("text", x = as.Date("2021-03-01",format = "%Y-%m-%d"), y = -25, size=3,label = "Johnson + Johnson,Visa, Infineon, McDonalds, Hella, Coty Inc.",color="orange3",hjust = 0, vjust=1)+
annotate("text", x = as.Date("2021-03-01",format = "%Y-%m-%d"), y = 2, size=3,label = "Realty Inc., Total, Siemens Energy, carnival, EPR PRoperties,",color="blue",hjust = 0, vjust=-0.5)+ 
annotate("text", x = as.Date("2021-03-01",format = "%Y-%m-%d"), y = 2, size=3,label = "Coca-Cola, Allianz, Altria Grp, Anheuser-Busch",color="blue",hjust = 0, vjust=1)+    
  
annotate("text", x = as.Date("2021-03-02",format = "%Y-%m-%d"), y = 2, size=3,label = "Rocket Comp.",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-03-02",format = "%Y-%m-%d"), y = -30, size=3,label = "Siemens Helath",color="orange3",hjust = 0)+  
  
annotate("text", x = as.Date("2021-03-08",format = "%Y-%m-%d"), y = 2, size=3,label = "Altria Grp",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-03-08",format = "%Y-%m-%d"), y = -30, size=3,label = "Xiaomi",color="orange3",hjust = 0)+  
  
annotate("text", x = as.Date("2021-03-11",format = "%Y-%m-%d"), y = 2, size=3,label = "Pembina Pipeline, American Shipping, Realty Inc.",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-03-11",format = "%Y-%m-%d"), y = -25, size=3,label = "Siemens Energy, Airbus, Siemens Health, Pernod-Ricard",color="orange3",hjust =0)+
  
annotate("text", x = as.Date("2021-03-12",format = "%Y-%m-%d"), y = 2, size=3,label = "RioCan Real Estate",color="blue",hjust = 0)+ 
annotate("text", x = as.Date("2021-03-12",format = "%Y-%m-%d"), y = -25, size=3,label = "Covestro",color="orange3",hjust =0)+  
  

  coord_flip()+
   scale_x_date(date_breaks = "1 day", date_labels = "%Y-%m-%d")+
  scale_y_continuous(breaks=c(seq(-1,1,by=1)),limits = c(-30,30), labels = function(x) ifelse(x<0, -x,x))+
  scale_fill_manual(values=c("blue","orange3"))

```

## Payed out dividends

```{r echo=F}

```

